### ISSUE TITLE
Change background color when toggling

### ISSUE THREAD

**Issue by LaymanTruant** [LaymanTruant/aoe2de#27]
For the current status, our UI maintain the same background color when toggling. We should change the background color of title block when we toggle to dark mode. 

<img width="604" alt="Screen Shot 2020-08-05 at 9 07 23 PM" src="https://user-images.githubusercontent.com/59020539/89416590-13f6e000-d760-11ea-82ec-e139d39ae16c.png">
<img width="601" alt="Screen Shot 2020-08-05 at 9 07 33 PM" src="https://user-images.githubusercontent.com/59020539/89416593-16f1d080-d760-11ea-9440-871476a592a4.png">

**Comment by milkoya** [comment]
verified in master
