### ISSUE TITLE
Disable to open page in new tab

### ISSUE THREAD

**Issue by LaymanTruant** [LaymanTruant/aoe2de#28]
When we click the item in catalog, we will be redirected to new tab. It should be disabled. 

The items what I mentioned are as follows:
<img width="393" alt="Screen Shot 2020-08-05 at 9 14 05 PM" src="https://user-images.githubusercontent.com/59020539/89417165-e8282a00-d760-11ea-910f-a7dab39b9f98.png">

**Comment by milkoya** [comment]
Verified in master
