### ISSUE TITLE
Page of contents does not redirect to the right section

### ISSUE THREAD

**Issue by LaymanTruant** [LaymanTruant/aoe2de#29]
**Current**
Look at following screenshot, when I click the quick link in the table of contents (red block), the page doesn't redirect to correct section.

<img width="1040" alt="Screen Shot 2020-08-05 at 9 18 40 PM" src="https://user-images.githubusercontent.com/59020539/89417851-d7c47f00-d761-11ea-92c0-62a7f6356775.png">

**Issue**
The Gatsby will retain scroll position for pages. In this case, when we want to redirect to difference anchors, the retained scroll position prevent the page from scrolling to anchor position.

**Solution**
Use Gatsby [Browser API getSavedScrollPosition](https://www.gatsbyjs.org/docs/browser-apis/#shouldUpdateScroll) to disable default scroll behavior (retain scroll position) when redirecting to anchors (hashtag).

**Comment by milkoya** [comment]
verified in master
